def pig script
 puts "running pig script #{script}"
 system("pig -x local -f #{script}")
end

task :clean do
 %w(unigram bigram trigram).each do |d|
  %w(s _c _f).each do |post|
   FileUtils.rm_rf "#{d}#{post}"
  end
 end
end

task :rebuild_ngrams => [:clean] do
 pig 'extract_ngrams.pig'
 pig 'ngram_freq_and_count.pig'
end